Fixed AttributeError: no attribute 'MaxCut'
AttributeError: module 'qaoa.problems' has no attribute 'MaxCut'

The MaxCut class was removed from the original repo OpenQuantumComputing/QAOA.
Solution: Forked the repo, cloned the forked repo and re-added the removed maxcut_problem.py file in the problems folder. From maxcut_problem.py imported MaxCut in the ___init__.py file in the problems folder (line 9).